export enum AuditEvent {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  OTP_SENT = 'OTP_SENT',
  OTP_VERIFIED = 'OTP_VERIFIED',
  OTP_FAILED = 'OTP_FAILED',
  MFA_SETUP = 'MFA_SETUP',
  MFA_ENABLED = 'MFA_ENABLED',
  MFA_VERIFIED = 'MFA_VERIFIED',
  MFA_FAILED = 'MFA_FAILED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  LOGOUT = 'LOGOUT',
  LOGOUT_ALL_DEVICES = 'LOGOUT_ALL_DEVICES',
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  RBAC_VIOLATION = 'RBAC_VIOLATION',
  
  // Phase 1: Project Requests & Client Onboarding
  CLIENT_LOGIN = 'CLIENT_LOGIN',
  CLIENT_PASSWORD_CHANGED = 'CLIENT_PASSWORD_CHANGED',
  PROJECT_REQUEST_SUBMITTED = 'PROJECT_REQUEST_SUBMITTED',
  PROJECT_REQUEST_APPROVED = 'PROJECT_REQUEST_APPROVED',
  PROJECT_REQUEST_REJECTED = 'PROJECT_REQUEST_REJECTED',
  CLIENT_ACCOUNT_CREATED = 'CLIENT_ACCOUNT_CREATED',
  
  // Phase 2: Client Dashboard
  PROJECT_VIEWED = 'PROJECT_VIEWED',
  DOCUMENT_VIEWED = 'DOCUMENT_VIEWED',
  DOCUMENT_DOWNLOADED = 'DOCUMENT_DOWNLOADED',
  MILESTONE_VIEWED = 'MILESTONE_VIEWED',
  PROJECT_UPDATE_VIEWED = 'PROJECT_UPDATE_VIEWED',
  
  // Phase 3: Tickets, Meetings, Documents
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_UPDATED = 'TICKET_UPDATED',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  TICKET_ESCALATED = 'TICKET_ESCALATED',
  TICKET_RESOLVED = 'TICKET_RESOLVED',
  TICKET_CLOSED = 'TICKET_CLOSED',
  
  DOCUMENT_SEARCHED = 'DOCUMENT_SEARCHED',
  
  MEETING_REQUESTED = 'MEETING_REQUESTED',
  MEETING_APPROVED = 'MEETING_APPROVED',
  MEETING_REJECTED = 'MEETING_REJECTED',
  MEETING_RESCHEDULED = 'MEETING_RESCHEDULED',
  
  // Phase 4: Billing & Razorpay
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_UPDATED = 'INVOICE_UPDATED',
  INVOICE_CANCELLED = 'INVOICE_CANCELLED',
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  RECEIPT_DOWNLOADED = 'RECEIPT_DOWNLOADED',

  // Phase 5: AI Assistant
  AI_QUERY = 'AI_QUERY',
  AI_DOCUMENT_RETRIEVAL = 'AI_DOCUMENT_RETRIEVAL',
  AI_PAYMENT_QUERY = 'AI_PAYMENT_QUERY',
  AI_TICKET_QUERY = 'AI_TICKET_QUERY',
  AI_MEETING_QUERY = 'AI_MEETING_QUERY',
  AI_RBAC_DENIED = 'AI_RBAC_DENIED',

  // Phase 7: Operations & Resilience
  SECURITY_ANOMALY_DETECTED = 'SECURITY_ANOMALY_DETECTED',
  THROTTLE_ABUSE_DETECTED = 'THROTTLE_ABUSE_DETECTED',
}
