import type { AgileTask, Sprint, Epic } from '../types/agile.types';

export const mockAssignees = {
  vijay: { userId: 'emp-001', name: 'Vijay Salvatore', avatar: 'https://i.pravatar.cc/150?u=emp-001' },
  arjun: { userId: 'emp-002', name: 'Arjun M.', avatar: 'https://i.pravatar.cc/150?u=emp-002' },
  priya: { userId: 'emp-003', name: 'Priya K.', avatar: 'https://i.pravatar.cc/150?u=emp-003' },
};

export const mockEpics: Epic[] = [
  { id: 'epic-1', key: 'MVP-10', name: 'Authentication System', color: 'bg-blue-500' },
  { id: 'epic-2', key: 'MVP-11', name: 'Dashboard Widget Engine', color: 'bg-purple-500' },
];

export const mockActiveSprint: Sprint = {
  id: 'sprint-14',
  name: 'Sprint 14',
  goal: 'Finalize authentication flows and dashboard widgets.',
  status: 'ACTIVE',
  startDate: '2026-06-23',
  endDate: '2026-07-07',
};

export const mockTasks: AgileTask[] = [
  {
    id: 'task-1',
    key: 'MVP-124',
    title: 'Implement JWT refresh token rotation',
    description: 'Ensure that refresh tokens are rotated on every use to prevent replay attacks.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    type: 'STORY',
    storyPoints: 5,
    assignee: mockAssignees.vijay,
    reporter: mockAssignees.arjun,
    sprintId: 'sprint-14',
    epicId: 'epic-1',
    labels: ['security', 'auth'],
    createdAt: '2026-06-20T10:00:00',
    updatedAt: '2026-07-02T14:30:00',
  },
  {
    id: 'task-2',
    key: 'MVP-125',
    title: 'Design MFA verification screens',
    description: 'Create high-fidelity mockups for the TOTP setup and verification flow.',
    status: 'REVIEW',
    priority: 'MEDIUM',
    type: 'TASK',
    storyPoints: 3,
    assignee: mockAssignees.priya,
    reporter: mockAssignees.vijay,
    sprintId: 'sprint-14',
    epicId: 'epic-1',
    labels: ['design', 'ui'],
    createdAt: '2026-06-21T09:15:00',
    updatedAt: '2026-07-03T11:00:00',
  },
  {
    id: 'task-3',
    key: 'MVP-128',
    title: 'Fix CSRF token mismatch on Firefox',
    description: 'Users on Firefox are randomly getting 403 Forbidden due to CSRF cookie parsing issues.',
    status: 'TODO',
    priority: 'CRITICAL',
    type: 'BUG',
    storyPoints: 2,
    assignee: mockAssignees.arjun,
    reporter: mockAssignees.vijay,
    sprintId: 'sprint-14',
    epicId: 'epic-1',
    labels: ['bug', 'auth'],
    createdAt: '2026-07-01T16:20:00',
    updatedAt: '2026-07-01T16:20:00',
  },
  {
    id: 'task-4',
    key: 'MVP-130',
    title: 'Create draggable Kanban column component',
    description: 'Build a reusable drag-and-drop column component for the agile board.',
    status: 'DONE',
    priority: 'HIGH',
    type: 'STORY',
    storyPoints: 5,
    assignee: mockAssignees.vijay,
    reporter: mockAssignees.priya,
    sprintId: 'sprint-14',
    epicId: 'epic-2',
    labels: ['frontend', 'react'],
    createdAt: '2026-06-24T08:00:00',
    updatedAt: '2026-06-28T17:45:00',
  },
  {
    id: 'task-5',
    key: 'MVP-135',
    title: 'Write unit tests for AuthStore',
    description: 'Add Jest tests covering Zustand store mutations and persist logic.',
    status: 'TESTING',
    priority: 'LOW',
    type: 'TASK',
    storyPoints: 2,
    assignee: mockAssignees.arjun,
    reporter: mockAssignees.vijay,
    sprintId: 'sprint-14',
    epicId: 'epic-1',
    labels: ['testing'],
    createdAt: '2026-06-25T11:30:00',
    updatedAt: '2026-07-02T09:15:00',
  },
  // Backlog tasks
  {
    id: 'task-6',
    key: 'MVP-140',
    title: 'Implement Dark Mode toggle in user preferences',
    description: 'Allow users to force dark mode regardless of system settings.',
    status: 'BACKLOG',
    priority: 'LOW',
    type: 'STORY',
    storyPoints: 3,
    reporter: mockAssignees.vijay,
    epicId: 'epic-2',
    labels: ['ui'],
    createdAt: '2026-07-02T10:00:00',
    updatedAt: '2026-07-02T10:00:00',
  }
];
