import type { Project } from '../types/projects.types';

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Mervi Platform v2',
    key: 'MVP',
    description: 'Next-generation internal workspace and CI/CD integration platform.',
    status: 'ACTIVE',
    health: 'ON_TRACK',
    progress: 72,
    startDate: '2026-01-15',
    targetDate: '2026-08-30',
    lead: { userId: 'emp-001', name: 'Vijay Salvatore', role: 'Lead Architect', avatar: 'https://i.pravatar.cc/150?u=emp-001' },
    team: [
      { userId: 'emp-002', name: 'Arjun M.', role: 'Backend Developer' },
      { userId: 'emp-003', name: 'Priya K.', role: 'UI/UX Designer' },
      { userId: 'emp-004', name: 'Sarah L.', role: 'QA Engineer' },
    ],
    budget: { allocated: 150000, spent: 85000, currency: 'USD' },
    stats: { totalTasks: 450, completedTasks: 324, openIssues: 12 },
    tags: ['Core', 'Platform', 'Q3-Release'],
  },
  {
    id: 'proj-2',
    name: 'Client Portal Redesign',
    key: 'CPR',
    description: 'Overhaul of the client-facing dashboard using Next.js and ShadCN.',
    status: 'COMPLETED',
    health: 'ON_TRACK',
    progress: 100,
    startDate: '2025-11-01',
    targetDate: '2026-03-15',
    lead: { userId: 'emp-005', name: 'David Chen', role: 'Product Manager' },
    team: [
      { userId: 'emp-001', name: 'Vijay Salvatore', role: 'Lead Architect' },
      { userId: 'emp-006', name: 'Elena R.', role: 'Frontend Developer' },
    ],
    budget: { allocated: 80000, spent: 78500, currency: 'USD' },
    stats: { totalTasks: 210, completedTasks: 210, openIssues: 0 },
    tags: ['Client', 'Frontend'],
  },
  {
    id: 'proj-3',
    name: 'Analytics Data Pipeline',
    key: 'ADP',
    description: 'Real-time data processing pipeline using Kafka and ClickHouse.',
    status: 'ACTIVE',
    health: 'AT_RISK',
    progress: 45,
    startDate: '2026-04-10',
    targetDate: '2026-09-15',
    lead: { userId: 'emp-007', name: 'Michael T.', role: 'Data Engineer' },
    team: [
      { userId: 'emp-002', name: 'Arjun M.', role: 'Backend Developer' },
      { userId: 'emp-008', name: 'Lisa W.', role: 'Data Scientist' },
    ],
    budget: { allocated: 120000, spent: 65000, currency: 'USD' },
    stats: { totalTasks: 180, completedTasks: 81, openIssues: 24 },
    tags: ['Data', 'Infrastructure'],
  },
  {
    id: 'proj-4',
    name: 'Mobile App Beta',
    key: 'MOB',
    description: 'React Native mobile application for employee portal access.',
    status: 'PLANNING',
    health: 'BEHIND',
    progress: 15,
    startDate: '2026-06-01',
    targetDate: '2026-12-01',
    lead: { userId: 'emp-009', name: 'James H.', role: 'Mobile Lead' },
    team: [
      { userId: 'emp-010', name: 'Anna P.', role: 'Mobile Developer' },
      { userId: 'emp-003', name: 'Priya K.', role: 'UI/UX Designer' },
    ],
    budget: { allocated: 200000, spent: 15000, currency: 'USD' },
    stats: { totalTasks: 320, completedTasks: 48, openIssues: 5 },
    tags: ['Mobile', 'Beta'],
  },
  {
    id: 'proj-5',
    name: 'Legacy API Migration',
    key: 'LAM',
    description: 'Migrating legacy v1 REST endpoints to GraphQL.',
    status: 'ON_HOLD',
    health: 'AT_RISK',
    progress: 60,
    startDate: '2025-08-01',
    targetDate: '2026-05-30',
    lead: { userId: 'emp-002', name: 'Arjun M.', role: 'Backend Developer' },
    team: [
      { userId: 'emp-011', name: 'Tom B.', role: 'Backend Developer' },
    ],
    budget: { allocated: 90000, spent: 75000, currency: 'USD' },
    stats: { totalTasks: 150, completedTasks: 90, openIssues: 8 },
    tags: ['Backend', 'Technical Debt'],
  }
];
